# This will run on Travis' 'new' container-based infrastructure
sudo: true

# Setup for Ubuntu Bionic (18.04)
dist: bionic

language:
  - python

python:
  - 3.6

# Environment variables
env:
  global:
    - PACKAGE_DIR: $HOME/packages
    - GH_REPO_NAME: rce-gen3-fw-lib
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/slaclab/rce-gen3-fw-lib.git
    - MINICONDA_DIR: $PACKAGE_DIR/miniconda
    - secure: "jbc5lyYqBjSWsIbQICNKFnLUfG3zVXS/N+ou26RmXqkXD/HufPJ4DpyIthXIfcLo2FGKeydm5nElCJG2h5OjvZ9x5E15F4rwXOP79+7FLMNCrwChDrDHhZ/fYFAhUInBx+5QOiI8+Innzm7DkdigTlJIbXIPwKz4V99n/AvTBvUyXO3pXnUZaUsIXr2x2dfy9IDt64e0koYPV+Hu42itwFuYNu5MWQdxclLNxmpw9HOHTsl7V6JM2F7K6BJ+7nMvnWghXHQ38STiaQtWoXIth2FlFEkTD1DqA2BCPNpxDWQGsr/NZ+jW2IVLHqh+sTJFebXfB9W2eNKAkONQ5p99WEDfU/9uCH/j3GbH13c1WwDX/y4u9De/QxiUBHbvWBt06ZaPlsU6mC4EA8DPJoqNEfY1sselUeFwCoUHdaxVElf/lvHLV5N17knzFJ6MotrTg+VdJNhil8ITOBFHX6vqi3rAWt4A65FKTBpyWJX/8nsbyQdr7WbJ7467G3HcBZnz77NdyeyIoD1E7oyrmeBNwUD27Arg4n/AW2GHM6GZPiXQVY0hr9evIfn6pvYsgBHOmUCh36rcHI9cewzyL4GvBsr3wmP5383zMxro1xB/HpsMuXMHZ6VXZ7apJj9IYvpwScA21OIP30IdGKBBO7CH0gXlV/qBMsbJnHZonyYk8pA="

# Install dependencies
addons:
  apt:
    packages:
      - python3

stages:
    - name: deploy_dev
      if: branch = pre-release AND tag IS blank AND NOT (type = pull_request)
    - name: deploy_tag
      if: tag IS present

# Generate and deploy documentation
jobs:
  include:
    - &deploy-conda-stage       # Conda for linux
      stage: deploy_dev
      name: "Deploy Conda"
      env: CONDA_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
      before_install:
        # Prepare folders
        - mkdir -p $MINICONDA_DIR
        # Bring all the tags
        - git pull --unshallow
        - git pull
        # on OSX rogue needs an older version of the MacOS SDK
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            git clone https://github.com/phracker/MacOSX-SDKs;
            sudo mv MacOSX-SDKs/MacOSX10.9.sdk /opt/;
            export CONDA_BUILD_SYSROOT=/opt/MacOSX10.9.sdk;
            export CONDA_BUILD=1;
          fi

      install:
        # Install Anaconda for the right architecture (linux or osx)
        - cd $MINICONDA_DIR
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
          else
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
          fi
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes
        - conda install conda-build anaconda-client conda-verify
        - conda update -q conda conda-build

      before_script:
        # Go back to top directory
        - cd $TRAVIS_BUILD_DIR

      script:
        # Build conda package
        - travis_wait 60 conda build --debug conda-recipe --output-folder bld-dir -c tidair-tag -c conda-forge

      after_success:
        # Upload conda package
        - anaconda -t $CONDA_TOKEN upload bld-dir/`echo $TRAVIS_OS_NAME`-64/*.tar.bz2

    - <<: *deploy-conda-stage   # Conda for MacOS
      os: osx
      language: ruby  # osx does not support language=python

    - <<: *deploy-conda-stage   # Conda for Linux
      stage: deploy_tag
      env: CONDA_TOKEN=$CONDA_UPLOAD_TOKEN_TAG

